// agents/tools/emailTool.ts
// Gmail SMTP via Nodemailer
//
// SETUP:
//   npm install nodemailer
//   npm install -D @types/nodemailer
//
// .env.local:
//   GMAIL_USER=yourname@gmail.com
//   GMAIL_APP_PASSWORD=abcdefghijklmnop
//   EMAIL_FROM=MindCare <yourname@gmail.com>

import nodemailer from "nodemailer";

interface WellnessSummaryEmail {
  to: string;
  userName: string;
  sentiment: "positive" | "negative";
  response: string;
  journalDate: string;
}

function createGmailTransporter() {
  const user = process.env.GMAIL_USER;
  const pass = process.env.GMAIL_APP_PASSWORD;

  if (!user || !pass) {
    console.error("[emailTool] Missing GMAIL_USER or GMAIL_APP_PASSWORD in .env");
  }

  return nodemailer.createTransport({
    service: "gmail",
    auth: {
      user,
      pass,
    },
  });
}

export async function sendWellnessSummaryEmail(
  payload: WellnessSummaryEmail
): Promise<boolean> {
  try {
    const transporter = createGmailTransporter();

    const isPositive = payload.sentiment === "positive";
    const color = isPositive ? "#10b981" : "#6366f1";
    const emoji = isPositive ? "🌟" : "💙";

    const subject = isPositive
      ? `🌟 Your MindCare Wellness Insight — ${payload.journalDate}`
      : `💙 Your MindCare Support Message — ${payload.journalDate}`;

    const html = `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
                  max-width:600px;margin:0 auto;padding:24px;background:#ffffff;">

        <h1 style="color:${color};margin:0 0 8px;font-size:24px;">
          ${emoji} MindCare
        </h1>

        <p style="color:#6b7280;font-size:14px;margin:0 0 24px;">
          Hi ${payload.userName}, here is your wellness insight from ${payload.journalDate}.
        </p>

        <div style="background:#f9fafb;border-left:4px solid ${color};
                    padding:20px;border-radius:8px;margin:0 0 24px;">
          ${payload.response
            .split("\n")
            .filter((l) => l.trim())
            .map(
              (p) =>
                `<p style="margin:0 0 12px;color:#111827;line-height:1.6;font-size:15px;">${p}</p>`
            )
            .join("")}
        </div>

        <p style="color:#9ca3af;font-size:12px;border-top:1px solid #f3f4f6;
                  padding-top:16px;margin:0;">
          This insight was generated by MindCare AI and reviewed by you before sending.
          A copy of this report may have been sent to the primary health contact on file.
          If you are experiencing a mental health crisis, please contact a professional.
        </p>

      </div>
    `;

    const text = [
      `MindCare Wellness Insight — ${payload.journalDate}`,
      `Hi ${payload.userName},`,
      "",
      payload.response,
      "",
      "Generated by MindCare AI, reviewed by you before sending.",
    ].join("\n");

    const mainReportEmail = process.env.MAIN_REPORT_EMAIL;

    await transporter.sendMail({
      from: process.env.EMAIL_FROM ?? `MindCare <${process.env.GMAIL_USER}>`,
      to: payload.to,
      cc: mainReportEmail || undefined, // Send a copy to the main address if defined
      subject,
      text,
      html,
    });

    console.log(`[emailTool] Gmail sent successfully to ${payload.to}`);
    return true;
  } catch (err: any) {
    console.error("[emailTool] Gmail SMTP error:", {
      message: err.message,
      code: err.code,
      command: err.command,
      response: err.response,
    });
    return false;
  }
}